### ISSUE TITLE
Edit Project (Add Project/Step 2)

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#10]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need** choose a icon and a project color
**to be able to** individualize my projects as my personal taste

# Description

<img width="258" alt="Bildschirmfoto 2022-05-11 um 12 22 08" src="https://user-images.githubusercontent.com/100295387/167828057-6bf34e6d-d009-4a3c-a5b0-ce124f02fdb1.png">

# Acceptance Criteria

- [ ] A border box with round corners is displayed
- [ ] A box within the box is displayed, labeled "Icon". Inside this, a list of icons is displayed a user can choose from
- [ ] A list of five circles is displayed, colored blue, purple, yellow, red and green. The circle-list is labeled "Projektfarbe". 
- [ ] Outside the border box a submit button is displayed, labeled "Nächster Schritt"

# Tasks

(for developers team)

- [ ] Add a new branch "edit-project-step-2"
- [ ] Create a box element with a `<section>` tag
- [ ] Inside this box, create a box element, labeled "Icon"
- [ ] Inside this box, create input-fields as radio-buttons. Each value of a button is an different icon.
- [ ] Create a input field with five radio buttons, labeled "Projektfarbe"
- [ ] The value of the radio buttons are colored circles

# Complexity

L

**Comment by NadineGrosskreuz** [comment]
Hey Mikail,
nice User Story!

**Comment by NadineGrosskreuz** [comment]
Hey Mikail,
nice User Story! 🚀 Just a few things:

- Your Value Proposition is not entirely correct. I would write it this way:
As a user
I need **to** choose **an** icon and a project color
to be able to individualize my projects **according to** my personal taste.
- In your scribble the language is English, in the criterias German. I would adjust it.
- I would think again about what you want to test
- Just typo:
Each value of a button is **a** different icon.
Create **a** input field

I like that your descriptions are very detailed!
