### ISSUE TITLE
Project View (Project)

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#13]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need** an overview of all my project contents
**to be able to** have an optimal view of my features and todoitems inside my project

# Description

<img width="191" alt="Project View (Project)" src="https://user-images.githubusercontent.com/100295387/168045283-6b8b46a4-1929-46a2-b695-104473fe6841.png">

# Acceptance Criteria

- [ ] A headline with a arrow is displayed, which can be clicked to choose between projects in a new selection box.
- [ ] On the top right corner, a information icon is displayed. If the icon is clicked, a new box with the begin date, end date and the project notes is displayed
- [ ] A list of all the feature components of the selected project is displayed
- [ ] A button at the bottom of the list is displayed, labeled "Feature hinzufügen"

# Tasks

(for developers team)

- [ ] Add a new branch "project-view-project"
- [ ] Create a headline as a `<h1>`tag at the top left corner, wrapped in a `<button>`tag.
- [ ] Create a selection box, to let the user choose between projects, if the headline button is clicked
- [ ] Set an information icon at the top right corner
- [ ] Create a paragraph inside a box, to let the user see the project information, if the icon is clicked
- [ ] The component receives the feature list component
- [ ] Create a button component at the bottom of the list, to add a new feature to the project
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered

# Complexity

L

**Comment by doemser** [comment]
Good Job for User-Story and AC!

Checked one of your tasks with a html validator and it says:
"Element h1 not allowed as child of element button"
