### ISSUE TITLE
Edit Feature (Project)

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#15]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need to** edit my feature
**to be able to** set a new name, begin date, end date and edit my todoitems

# Description

<img width="213" alt="Edit Feature (Project)" src="https://user-images.githubusercontent.com/100295387/168075395-c441f063-974f-49d2-9d2d-fd500fd32381.png">

# Acceptance Criteria

- [ ] A headline for the current project name is displayed
- [ ] On the top right corner a close icon is displayed. If the icon is clicked, the edit view closes and leads the user back to the "Feature View (Project)" component
- [ ] A border box with round corners is displayed
- [ ] An input field for the feature name is displayed, labeled "Featurename". This field is editable and contains the saved feature name a user took on his todoitem
- [ ] An input field for the begin date is displayed, labeled "Startdatum". This field is editable and contains the saved begin date a user chose on his todoitem
- [ ] An input field for the end date is displayed, labeled "Enddatum". This field is editable and contains the saved end date a user chose on his todoitem
- [ ] A list of the saved todoitems are displayed as multiple boxes
- [ ] A button at the bottom of the list is displayed, labeled "Fertig"

# Tasks

(for developers team)

- [ ] Add a new branch "edit-feature-project"
- [ ] Create a headline as a `<h1>` tag at the top left corner
- [ ] Set an close icon wrapped in a `<button>` tag at the top right corner of the edit box
- [ ] Create a box element within a `<section>` tag
- [ ] Create a input field with a label and the name content of the chosen feature
- [ ] Create a input component with date validation and a label (for field "Startdatum")
- [ ] Create a input component with date validation and a label (for field "Enddatum")
- [ ] The component receives the TodoItemList component
- [ ] Inside the Todoitem box, the colored circle for complexity is displayed on the right side
- [ ] Inside the Todoitem box, a edit icon is displayed on the left side. If the icon is clicked, it leads the user to the "Edit Todoitem (Project)" component
- [ ] Create a button component at the bottom of the list, to finish the editing and submit the new data to the chosen feature

# Complexity

XL
