### ISSUE TITLE
Feature Card List (Project)

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#16]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need** an overview of all my projects
**to be able to** have a detailed list of all my projects with the features

# Description

<img width="158" alt="Project List (Home)" src="https://user-images.githubusercontent.com/100295387/168079449-9232c341-cde8-48ed-a27d-2264acac3311.png">

# Acceptance Criteria

- [ ] A headline "Meine Projekte" is displayed at the top left corner
- [ ] A list of all the project components is displayed

# Tasks

(for developers team)

- [ ] Add a new branch "project-list-home"
- [ ] Create a headline as a `<h1>`tag at the top left corner
- [ ] The component receives all of the project card components
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered

# Complexity

M

**Comment by irenepapaspyratos** [comment]
The component receives all of the project card components **as/in an array**   ?
