### ISSUE TITLE
Add Feature (Project)

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#17]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need** add a new feature to my feature list
**to be able to** increase the variety of available features for a single project right in my project page

# Description

<img width="165" alt="Add Feature (Project)" src="https://user-images.githubusercontent.com/100295387/168081329-ae529ca0-fbf0-4a12-b82b-28b06f978d1f.png">

# Acceptance Criteria

- [ ] A headline for the current project name is displayed
- [ ] On the top right corner a close icon is displayed. If the icon is clicked, the edit view closes and leads the user back to the "Project View (Project)" component
- [ ] A border box with round corners is displayed
- [ ] The component "Add Feature (Add Project)" is displayed
- [ ] Outside the border box a submit button is displayed, labeled "Fertig"

# Tasks

(for developers team)

- [ ] Add a new branch "add-feature-project"
- [ ] Create a headline as a `<h1>` tag at the top left corner
- [ ] Set an close icon wrapped in a `<button>` tag at the top right corner of the box
- [ ] Create a box element within a `<section>` tag
- [ ] The component receives the "Add Feature (Add Project)" component
- [ ] Create a button component at the bottom of the list, to submit the new data to the feature list
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered

# Complexity

M
