### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#20]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need** a navigation menu
**to be able to** switch through pages inside my app

# Description

<img width="288" alt="Footer" src="https://user-images.githubusercontent.com/100295387/168475285-b329b409-fea2-4476-8cf6-a8fa7e69b0f3.png">

# Acceptance Criteria

- [ ] A light grey box is displayed
- [ ] Inside this box, a list of three icons are displayed (Home, Add Project and Project)
- [ ] The icon on the active page has a different color 

# Tasks

(for developers team)

- [ ] Add a new branch "footer"
- [ ] Create an unordered list inside the `<footer>`, to list the different icons
- [ ] Wrap the list items into `<button>`, to make them clickable
- [ ] Link the buttons to the related pages
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app

# Complexity

**Comment by NadineGrosskreuz** [comment]
Hey Mikail,
are you sure this is your next User Story following this one #10 ?
Maybe I would work on this step before 
The button leads the user to the "User Question (Add Project)" component.

Otherwise, here are my comments to the User Story:
- I would only use the icons you need right now and add them, when you are adding the associated page
- I would think again about what you want to test

Happy coding! :)

**Comment by mikailsayan** [comment]
Hey Nadine,

thank you for your feedback. I used this story to code my Layout.js and fix it on the beginning. So next step would be #10 👍
