### ISSUE TITLE
Feature Component

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#3]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** logged in User
**I need** an overview of my feature in one card
**to be able to** define my feature and seperate it from others

# Description

<img width="362" alt="Bildschirmfoto 2022-05-06 um 11 12 06" src="https://user-images.githubusercontent.com/100295387/167102962-2dd81585-f12c-45f7-bbc5-8c95bad9cac4.png">

# Acceptance Criteria

- [ ] A border box is displayed with a checkbox and the feature name as a headline
- [ ] A status box is displayed with the current status information of the project like "0 / 4"
- [ ] A list of multiple boxes are displayed as "todo items"
- [ ] The first todo-item-box is light-grey to mark it as "last done"
- [ ] "Keine Todos" is displayed if list is empty

# Tasks

(for developers team)

- [ ] Create a new branch "feature-card"
- [ ] Create a new component to render the project card in a <section> Tag
- [ ] The component receives the "TodoList" component
- [ ] Set first Todo-box-color to light grey
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered

# Complexity

M

**Comment by mbosselmann** [comment]
Hi Mikail,
I like your user story! 👍 I only have one comment:

- I think you don't need to create a new component for this feature. It may be possible to reuse the other component that you described in the user story I reviewed yesterday. :D But that is something you will explore during implementing this feature. :)
