### ISSUE TITLE
Add Project Card

### ISSUE THREAD

**Issue by mikailsayan** [mikailsayan/capstone-project#9]

**Comment by mikailsayan** [comment]
# Value Proposition

**As a** user
**I need to** add a new project to my project list
**to be able to** increase the variety of available projects for my workbench.

# Description

<img width="255" alt="Add Project Card" src="https://user-images.githubusercontent.com/100295387/167139068-8d9e985e-4e06-4ffd-bd36-d18d4ff4e66f.png">

# Acceptance Criteria

- [ ] A border box with round corners is displayed
- [ ] An input field for the feature name is displayed, labeled "Projekt Name"
- [ ] A dropbox input field for the selection of the workbench is displayed, labeled "Workbench"
- [ ] An input field for notes is displayed, labeled "Notizen"
- [ ] An input field for the begin date is displayed, labeled "Startdatum:"
- [ ] An input field for the end date is displayed, labeled "Enddatum:"
- [ ] After the input fields for begin and end date, a calender icon is displayed

# Tasks

(for developers team)

- [ ] Add a new branch "add-project"
- [ ] Create a form component
- [ ] Create a input component with a label for the project name
- [ ] Create a input component with dropbox selection and a label for the workbench
- [ ] Create a input component with a label for the notes
- [ ] Create a input component with date validation (for field "Startdatum") and the calender icon
- [ ] Create a input component with date validation (for field "Enddatum") and the calender icon
- [ ] Form fields are controlled within a state
- [ ] Mark all form fields as required, except the notes input
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered

# Complexity

L

**Comment by mbosselmann** [comment]
Hi Mikail,
I think your user story is good except for one aspect: What will happen after submitting the new project? I think you have a component already which you want to use to render the output. If so then you should link to the user story and describe here what will happen with the data. That's all. :)
